name = "Cyclotomics"
uuid = "da8f5974-afbb-4dc8-91d8-516d5257c83b"
authors = ["Marek Kaluba <kalmar@amu.edu.pl>"]
version = "0.1.5"

[deps]
LRUCache = "8ac3fa9e-de4c-5943-b1dc-09c6b5f20637"
Memoize = "c03570c3-d221-55d1-a50c-7939bbd78826"
Primes = "27ebfcd6-29c5-5fa9-bf4b-fb8fc14df3ae"
SparseArrays = "2f01184e-e22b-5df5-ae63-d93ebab69eaf"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[compat]
LRUCache = "1.2"
Memoize = "0.4"
Primes = "0.4, 0.5"
julia = "1"
